### ISSUE TITLE
Weapon selection text misaligned on 1440p

### ISSUE THREAD

**Issue by TheOnly8Z** [DyaMetR/hl2hud#1]
When using 2560x1440 as my resolution, weapon selection text has inconsistent height. The effect seems to vary by font size and boldness but is always noticeable. Switching to 1920x1080 on the same setup makes the issue go away.

Does not appear to be an issue on any other text.

1440p, Verdana
![gm_construct0084](https://user-images.githubusercontent.com/13565172/229310773-064f0fad-dbb0-45bd-af44-07238e0b6cd4.jpg)

1440p, Arial
![gm_construct0085](https://user-images.githubusercontent.com/13565172/229310849-f1827534-a897-4c7d-be3a-3e93a9951481.jpg)

1440p, Cogan Light
![gm_construct0087](https://user-images.githubusercontent.com/13565172/229310898-9dc90d72-b52d-44d4-9cf7-44e796745e7c.jpg)

1080p, Verdana
![gm_construct0086](https://user-images.githubusercontent.com/13565172/229310844-6011fb50-6fdc-4eb0-b459-aa86d6709b7b.jpg)

1440p, Scheme editor is unaffected
![image](https://user-images.githubusercontent.com/13565172/229310885-f53c7f90-7c45-4580-9a03-2ed5c01fc202.png)

**Comment by DyaMetR** [comment]
Fixed in 9580da0.
