### ISSUE TITLE
Error when attempting to reset font

### ISSUE THREAD

**Issue by TheOnly8Z** [DyaMetR/hl2hud#2]
To replicate, open "Edit current scheme" and click reset font button on any font. Error seems to appear regardless of the current font value.

![image](https://user-images.githubusercontent.com/13565172/229311203-56e12ec2-a355-494b-92fd-5eef9c6ec10a.png)

```
[Half-Life 2 Customizable HUD] lua/autorun/hl2hud/qmenu/menu.lua:361: attempt to index global 'client' (a nil value)
  1. DoClick - lua/autorun/hl2hud/qmenu/menu.lua:361
   2. OnMouseReleased - lua/vgui/dlabel.lua:237
    3. unknown - lua/vgui/dimagebutton.lua:103
```

**Comment by DyaMetR** [comment]
Solved in d91c9ad.
