### ISSUE TITLE
Error when editing StopAnimation sequence

### ISSUE THREAD

**Issue by Sectonid** [DyaMetR/hl2hud#3]
The error appears when you click on "Edit animation command"
GMod console:
```
[Half-Life 2 Customizable HUD] lua/autorun/hl2hud/vgui/animations/editors/dcommandeditor.lua:58: attempt to index field 'Param2' (a nil value)
  1. PopulateFields - lua/autorun/hl2hud/vgui/animations/editors/dcommandeditor.lua:58
   2. DoClick - lua/autorun/hl2hud/qmenu/menu.lua:549
    3. OnMouseReleased - lua/vgui/dlabel.lua:237
     4. unknown - lua/vgui/dimagebutton.lua:103 (x2)
```

Also you can't save changes or delete that sequence.

Here's the video if that's gonna be useful:

https://user-images.githubusercontent.com/94748461/229333612-ea221fad-d43c-4992-96d1-ef1be4963779.mp4

**Comment by DyaMetR** [comment]
Solved in d91c9ad.
