### ISSUE TITLE
The weapon you have selected gets saved

### ISSUE THREAD

**Issue by WolfeStrider** [DyaMetR/hl2hud#4]
What I mean is basically when your using either the scroll wheel or the numbers to change your weapon this HUD addon remembers which weapon you last selected for that column even though the default ClientScheme HUD does not.

**Steps to reproduce:**
ClientScheme HUD:
Press 1 then click
*You equip the Crowbar
Press 1 then click
*You equip the Crowbar
Press 1 then click
*You equip the Crowbar

This addon's HUD:
Press 1 then click
*You equip the Crowbar
Press 1 then click
*You equip the Gravity Gun
Press 1 then click
*You equip the Physics Gun

**Comment by DyaMetR** [comment]
Solved in d91c9ad.
