### ISSUE TITLE
Most HL2 weapon HUD icons don't show up in 4K

### ISSUE THREAD

**Issue by WolfeStrider** [DyaMetR/hl2hud#6]
The only HL2 weapon HUD icons I can see are the pistol, (without the yellow scanline HUD effects) the grenade.

**Screenshot:**
![image](https://user-images.githubusercontent.com/47306808/229367976-df37be5e-3ba0-491e-bb08-e57c0baf4ade.png)

**Comment by DyaMetR** [comment]
Workaround added in 9580da0.
I'm sorry, after investigating a bit turns out some glyphs do not render at all past a certain size, so I had to add a scale limiter (which can be turned off).
