### ISSUE TITLE
Wrong font sizes

### ISSUE THREAD

**Issue by 0x5066** [DyaMetR/hl2hud#8]
**Describe the problem.**
HudHintSmall and HudSelectionText have the wrong parameters, both being font size and antialias.
To fix this, HudHintSmall's fontsize needs to be set to 7, and antialiasing is disabled, HudSelectionText's fontsize needs to be set to 6, and antialiasing is also disabled.

**How to reproduce.**
~~Provide a brief set of instructions to reproduce said problem.~~

**Lua errors**
~~Post any errors that may popup. This is very important.~~

**Potential conflict**
~~In case of the problem being related to an addon post either a download link or link its GitHub repository.~~
~~+   The download link must come from a reputable website (preferably the Steam Workshop or garrysmods.org).~~
~~+   If you can't provide a download link because the problem is being caused by a private addon contact its author instead.~~

**Additional information**
+   EndeavourOS, running in Proton.
+   Default branch.

**Comment by DyaMetR** [comment]
This addon approach to font scaling differs from vanilla HUD for convenience sake, sacrificing accuracy in the process.
Fonts have been set up to look as closely as possible to vanilla HUD at 1080p, a commonly used resolution.
Apologies for the inconvenience it might cause on your end.
