### ISSUE TITLE
Customization menu causes errors, again

### ISSUE THREAD

**Issue by somefnfplayerlol** [DyaMetR/hl2hud#9]
**Describe the problem.**
The customization menu causes an error if you attempt to save or apply your edited scheme. Also the button stays selected.

**How to reproduce.**
Click 'OK' or 'Apply' in the customization menu.

**Lua errors**
If reproduced correctly, this error should appear in the console:
```
[Half-Life 2 Customizable HUD] lua/includes/extensions/table.lua:60: bad argument #1 to 'next' (table expected, got nil)
  1. next - [C]:-1
   2. IsEmpty - lua/includes/extensions/table.lua:60
    3. ApplyScheme - lua/autorun/hl2hud/qmenu/menu.lua:109
     4. DoClick - lua/autorun/hl2hud/vgui/dframe.lua:55
      5. unknown - lua/vgui/dlabel.lua:237
```

**Potential conflict**
~~In case of the problem being related to an addon post either a download link or link its GitHub repository.~~
~~+   The download link must come from a reputable website (preferably the Steam Workshop or garrysmods.org).~~
~~+   If you can't provide a download link because the problem is being caused by a private addon contact its author instead.~~

**Additional information**
+   Windows 10.
+   The default Garry's Mod branch.

**Comment by DyaMetR** [comment]
Fixed in a863fdd.
